In [2]:
import cv2
from datetime import datetime
import numpy as np 

while True: 
    #파렛트 준비 
    img = np.full((500,500,3),255,dtype=np.uint8)

    #시계 원 
    c_radius = 200
    cv2.circle(img,(250,250),c_radius,(255,0,0),-1)
    
    #시간 표시 
    num_clock = np.arange(1,13,1,dtype=int)
    for index in num_clock:        
        hours = index
        xh = (c_radius-25)*np.cos(np.pi/180*(30*(hours-3)))
        yh = (c_radius-25)*np.sin(np.pi/180*(30*(hours-3)))
        print(xh,yh)
        #cv2.line(img,(250,250),(250+int(xh),250+int(yh)),(250,100,0),2)
        cv2.putText(img,str(hours),(int(238+xh),int(257+yh)),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),2,-1)

    cur_time = str(datetime.today().time())
    print(cur_time)
    cur_hour = int(cur_time[:2])
    cur_min = int(cur_time[3:5])
    cur_sec= int(cur_time[6:8])
    cur_time = f'{cur_hour}:{cur_min}:{cur_sec}'
    cv2.putText(img,cur_time,(10,50),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),2,-1)

    #초침 green
    cur_sec = cur_sec - 15
    xs = c_radius*np.cos(np.pi/180*(6*cur_sec))
    ys = c_radius*np.sin(np.pi/180*(6*cur_sec))
    print(xs,ys)
    cv2.line(img,(250,250),(250+int(xs),250+int(ys)),(0,255,100),2)

    #분침 red
    cur_min_forhour = cur_min
    cur_min = cur_min - 15 #360/60 = 6도씩 . 90도를 움직이려면 15*6 = 90 
    xm = c_radius*2/3*np.cos(np.pi/180*(6*cur_min))
    ym = c_radius*2/3*np.sin(np.pi/180*(6*cur_min))
    print(xm,ym)
    cv2.line(img,(250,250),(250+int(xm),250+int(ym)),(0,100,200),2)

    #시침
    #cur_hour = 0
    cmin_fh = cur_min_forhour*0.5 #분침에 따른 추가 이동 각도
    cur_hour = (cur_hour%12) -3 #360/12 = 30 도씩. 90도를 움직이려면 30*3 = 90 
    print(cur_hour)
    xh = c_radius/3*np.cos(np.pi/180*(30*cur_hour+cmin_fh))
    yh = c_radius/3*np.sin(np.pi/180*(30*cur_hour+cmin_fh))
    print(xh,yh)
    cv2.line(img,(250,250),(250+int(xh),250+int(yh)),(250,100,0),2)
    cv2.imshow("clock",img)
    
    if cv2.waitKey(1000) & 0xFF ==13: #주요 특수키 코드: 27(ESC), 13(ENTER), 9(TAB)
        break
     
cv2.destroyAllWindows()
    
    





87.50000000000001 -151.55444566227675
151.55444566227678 -87.49999999999999
175.0 0.0
151.55444566227678 87.49999999999999
87.50000000000001 151.55444566227675
1.0715659492539341e-14 175.0
-87.49999999999996 151.55444566227678
-151.55444566227678 87.49999999999999
-175.0 2.1431318985078682e-14
-151.55444566227675 -87.50000000000001
-87.50000000000007 -151.55444566227675
-3.214697847761802e-14 -175.0
16:20:56.055457
-81.34732861516002 -182.7090915285202
115.47005383792516 66.66666666666666
1
51.06962954126521 42.852507312435954
87.50000000000001 -151.55444566227675
151.55444566227678 -87.49999999999999
175.0 0.0
151.55444566227678 87.49999999999999
87.50000000000001 151.55444566227675
1.0715659492539341e-14 175.0
-87.49999999999996 151.55444566227678
-151.55444566227678 87.49999999999999
-175.0 2.1431318985078682e-14
-151.55444566227675 -87.50000000000001
-87.50000000000007 -151.55444566227675
-3.214697847761802e-14 -175.0
16:20:57.099687
-61.80339887498951 -190.2113032590307
115.470053

In [19]:
import cv2
from datetime import datetime
import numpy as np 

# while True: 
    #파렛트 준비 
img = np.full((500,500,3),255,dtype=np.uint8)
myimg = cv2.imread('images/baboon.jpg')
myimg = cv2.resize(myimg,(500,500))

#시계 원 
c_radius = 200
cv2.circle(img,(250,250),c_radius,(255,0,0),-1)
imageGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(imageGray, 250, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask) #mask 
print(imageGray, np.min(imageGray),np.max(imageGray))

img1_fg = cv2.bitwise_and(img, img, mask=mask)
img2_fg = cv2.bitwise_and(myimg, myimg, mask=mask_inv)
#img2_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)

cv2.imshow("img",img)
cv2.imshow("mask",mask)
cv2.imshow("mask_inv",mask_inv)
cv2.imshow("img1_fg",img1_fg)
cv2.imshow("img2_fg",img2_fg)
# cv2.imshow("mask_inv",mask)


cv2.waitKey(0)

cv2.destroyAllWindows()
    
#     #시간 표시 
#     num_clock = np.arange(1,13,1,dtype=int)
#     for index in num_clock:        
#         hours = index
#         xh = (c_radius-25)*np.cos(np.pi/180*(30*(hours-3)))
#         yh = (c_radius-25)*np.sin(np.pi/180*(30*(hours-3)))
#         print(xh,yh)
#         #cv2.line(img,(250,250),(250+int(xh),250+int(yh)),(250,100,0),2)
#         cv2.putText(img,str(hours),(int(238+xh),int(257+yh)),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),2,-1)

#     cur_time = str(datetime.today().time())
#     print(cur_time)
#     cur_hour = int(cur_time[:2])
#     cur_min = int(cur_time[3:5])
#     cur_sec= int(cur_time[6:8])
#     cur_time = f'{cur_hour}:{cur_min}:{cur_sec}'
#     cv2.putText(img,cur_time,(10,50),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),2,-1)

#     #초침 green
#     cur_sec = cur_sec - 15
#     xs = c_radius*np.cos(np.pi/180*(6*cur_sec))
#     ys = c_radius*np.sin(np.pi/180*(6*cur_sec))
#     print(xs,ys)
#     cv2.line(img,(250,250),(250+int(xs),250+int(ys)),(0,255,100),2)

#     #분침 red
#     cur_min_forhour = cur_min
#     cur_min = cur_min - 15 #360/60 = 6도씩 . 90도를 움직이려면 15*6 = 90 
#     xm = c_radius*2/3*np.cos(np.pi/180*(6*cur_min))
#     ym = c_radius*2/3*np.sin(np.pi/180*(6*cur_min))
#     print(xm,ym)
#     cv2.line(img,(250,250),(250+int(xm),250+int(ym)),(0,100,200),2)

#     #시침
#     #cur_hour = 0
#     cmin_fh = cur_min_forhour*0.5 #분침에 따른 추가 이동 각도
#     cur_hour = (cur_hour%12) -3 #360/12 = 30 도씩. 90도를 움직이려면 30*3 = 90 
#     print(cur_hour)
#     xh = c_radius/3*np.cos(np.pi/180*(30*cur_hour+cmin_fh))
#     yh = c_radius/3*np.sin(np.pi/180*(30*cur_hour+cmin_fh))
#     print(xh,yh)
#     cv2.line(img,(250,250),(250+int(xh),250+int(yh)),(250,100,0),2)
#     cv2.imshow("clock",img)
    
#     if cv2.waitKey(1000) & 0xFF ==13: #주요 특수키 코드: 27(ESC), 13(ENTER), 9(TAB)
#         break
     
# cv2.destroyAllWindows()
    
    





[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]] 29 255
