In [2]:
import cv2
import matplotlib.pyplot as plt
import numpy as np 

In [25]:
import cv2
import matplotlib.pyplot as plt

img = cv2.imread("./images/airplane1.jpg")
print(img.shape)
print(img)
cv2.imshow("airplane_origin",img)

#img2 = cv2.imread("./images/airimg1.jpg", cv2.IMREAD_GRAYSCALE)
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(img_gray.shape)
print(img_gray)
cv2.imshow("airplane_gray",img_gray)

img_hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
print(img_hsv.shape)
cv2.imshow("airplane_hsv",img_hsv)

img_ycrcb = cv2.cvtColor(img,cv2.COLOR_BGR2YCrCb)
print(img_ycrcb.shape)
cv2.imshow("airplane_ycrcb",img_ycrcb)
cv2.waitKey(0)
cv2.destroyAllWindows()


(427, 640, 3)
[[[193 163 138]
  [193 163 138]
  [193 163 138]
  ...
  [195 162 129]
  [194 161 128]
  [194 161 128]]

 [[193 163 138]
  [193 163 138]
  [193 163 138]
  ...
  [194 161 128]
  [194 161 128]
  [194 161 128]]

 [[193 163 138]
  [193 163 138]
  [193 164 137]
  ...
  [194 161 128]
  [194 161 128]
  [193 160 127]]

 ...

 [[182 158 136]
  [184 160 138]
  [182 158 136]
  ...
  [179 155 133]
  [179 155 133]
  [179 155 133]]

 [[182 158 136]
  [184 160 138]
  [182 158 136]
  ...
  [179 155 133]
  [179 155 133]
  [179 155 133]]

 [[182 158 136]
  [184 160 138]
  [182 158 136]
  ...
  [179 155 133]
  [179 154 134]
  [179 154 134]]]
(427, 640)
[[159 159 159 ... 156 155 155]
 [159 159 159 ... 155 155 155]
 [159 159 159 ... 155 155 154]
 ...
 [154 156 154 ... 151 151 151]
 [154 156 154 ... 151 151 151]
 [154 156 154 ... 151 151 151]]
(427, 640, 3)
(427, 640, 3)


In [8]:
##########################
# BGR SPLIT AND MERGE 
#####################

import cv2
import matplotlib.pyplot as plt

img = cv2.imread("./images/airplane1.jpg")
cv2.imshow("airplane_origin",img)
b,g,r =cv2.split(img)
cv2.imshow("b_airplane",b)
cv2.imshow("g_airplane",g)
cv2.imshow("r_airplane",r)
dst = cv2.merge([b,g,r])
cv2.imshow("dst",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
##########################
# BGR TO HSV
#####################

img = cv2.imread("./images/airplane1.jpg")

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.imshow("hsv",hsv)

print(hsv)
hue_val, sat_val, val_val = cv2.split(hsv)

cv2.imshow("src", img)

#hsv로 변환된 데이터는 아래와 같이 imshow를 보는 것은 의미없다 
cv2.imshow("hue",hue_val)
cv2.imshow("saturation",sat_val)
cv2.imshow("value",val_val)

print(hue_val.shape, sat_val.shape, val_val.shape)
dst= cv2.merge([hue_val,sat_val,val_val])
cv2.imshow("dst",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[106  73 193]
  [106  73 193]
  [106  73 193]
  ...
  [105  86 195]
  [105  87 194]
  [105  87 194]]

 [[106  73 193]
  [106  73 193]
  [106  73 193]
  ...
  [105  87 194]
  [105  87 194]
  [105  87 194]]

 [[106  73 193]
  [106  73 193]
  [106  74 193]
  ...
  [105  87 194]
  [105  87 194]
  [105  87 193]]

 ...

 [[106  64 182]
  [106  64 184]
  [106  64 182]
  ...
  [106  66 179]
  [106  66 179]
  [106  66 179]]

 [[106  64 182]
  [106  64 184]
  [106  64 182]
  ...
  [106  66 179]
  [106  66 179]
  [106  66 179]]

 [[106  64 182]
  [106  64 184]
  [106  64 182]
  ...
  [106  66 179]
  [107  64 179]
  [107  64 179]]]
(427, 640) (427, 640) (427, 640)


In [2]:
##########################
# BGR TO YCRCB
# 영상의 색감은 유지하고, 명암비를 높이기 
#####################
import cv2


file_list = ["./images/airplane1.jpg", "./images/house.jpg", 
             "./images/baboon.jpg", "./images/flower2.jpg",
             "./images/red_sky.jpg", "./images/puppies.jpg"]


for i, file in enumerate(file_list) :
    img = cv2.imread(file)
    img_ycrcb = cv2.cvtColor(img, cv2.COLOR_BGR2YCR_CB)
    print(img_ycrcb)
    y, cr, cb = cv2.split(img_ycrcb) # y_luminance, cr_val, cb_val 

    y = cv2.equalizeHist(y)
    img_after_eqHist = cv2.merge([y,cr,cb])
    img_final = cv2.cvtColor(img_after_eqHist, cv2.COLOR_YCR_CB2BGR)
    cv2.imshow(f"before{i}",img)
    cv2.imshow(f"after{i}",img_final)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[159 113 147]
  [159 113 147]
  [159 113 147]
  ...
  [156 109 150]
  [155 109 150]
  [155 109 150]]

 [[159 113 147]
  [159 113 147]
  [159 113 147]
  ...
  [155 109 150]
  [155 109 150]
  [155 109 150]]

 [[159 113 147]
  [159 113 147]
  [159 112 147]
  ...
  [155 109 150]
  [155 109 150]
  [154 109 150]]

 ...

 [[154 115 144]
  [156 115 144]
  [154 115 144]
  ...
  [151 115 144]
  [151 115 144]
  [151 115 144]]

 [[154 115 144]
  [156 115 144]
  [154 115 144]
  ...
  [151 115 144]
  [151 115 144]
  [151 115 144]]

 [[154 115 144]
  [156 115 144]
  [154 115 144]
  ...
  [151 115 144]
  [151 116 144]
  [151 116 144]]]
[[[ 41 150 127]
  [ 43 147 127]
  [ 45 143 129]
  ...
  [251 128 128]
  [251 128 128]
  [251 128 128]]

 [[ 55 149 127]
  [ 49 147 127]
  [100 142 127]
  ...
  [251 128 128]
  [251 128 128]
  [251 128 128]]

 [[ 55 148 127]
  [118 145 126]
  [126 140 125]
  ...
  [251 128 128]
  [251 128 128]
  [251 128 128]]

 ...

 [[187 129 123]
  [188 129 123]
  [187 129 123]
  ..

KeyboardInterrupt: 

In [30]:
import os
# file_list = os.listdir('images')
# for _file in file_list: 
#     print(_file)

#flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
    
with os.scandir('images') as file_list: 
    for _file in file_list:
        print(_file.name)

.gitignore
640px-Big_Tree_with_Red_Sky_in_the_Winter_Night.jpg
airplane.jpg
airplane1.jpg
airplane2-maskpoint.jpg
airplane2.jpg
baboon.jpg
bad_rectangle.png
butterfly.jpg
couple2.jpg
couple256.jpg
couple_flatening.png
digits.png
digits2.png
five.png
flower1.jpg
flower2.jpg
four.png
goal.mp4
goal2.mp4
gradation.png
gradients.jpg
house-full.jpg
house.jpg
j.png
j_noise.png
lena-256.jpg
lena.jpg
lena_bin.jpg
lena_canny.jpg
lena_dithering.jpg
lena_edge.png
lena_gray_dithering.jpg
lena_roi.jpg
lena_std_5.jpg
len_std_5.jpg
lightning.png
logo.png
mnist_test.jpg
mnist_test_c.jpg
opencv-logo-1.png
opening.png
paper.jpg
Puppies-HD.mp4
puppies.jpg
red_sky+airplane.jpg
red_sky.jpg
resize-100to50_area.png
resize-100to50_cubic.png
resize-100to50_lanczos4.png
resize-100to50_linear.png
resize-100to50_linear_exact.png
resize-100to50_nearest.png
resize-100to5_area.png
resize-100to5_cubic.png
resize-100to5_lanczos4.png
resize-100to5_linear.png
resize-100to5_linear_exact.png
resize-100to5_nearest.png
resiz

In [23]:
import cv2 
import numpy as np 

x = np.uint8([250])
y = np.uint8([10])
print( cv2.add(x,y) ) # 250+10 = 260 => 255
print( x+y ) 

[[260.]
 [  0.]
 [  0.]
 [  0.]]
[4]


In [15]:
##########################
# THRESHOLD 및 MASK 사용하기 
#####################

import cv2
import numpy as np

img1 = cv2.imread('images/logo.png')
img2 = cv2.imread('images/lena.jpg')

# 삽입할 이미지의 row, col, channel정보
rows, cols, channels = img1.shape

# 대상 이미지에서 삽입할 이미지의 영역을 추출
roi = img2[0:rows, 0:cols]

#mask를 만들기 위해서 img1을 gray로 변경후 binary image로 전환
#mask는 logo부분이 흰색(255), 바탕은 검은색(0)
#mask_inv는 logo부분이 검은색(0), 바탕은 흰색(255)

img2gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)

#bitwise_and 연산자는 둘다 0이 아닌 경우만 값을 통과 시킴.
#즉 mask가 검정색이 아닌 경우만 통과가 되기때문에 mask영역 이외는 모두 제거됨.
#아래 img1_fg의 경우는 bg가 제거 되고 fg(logo부분)만 남게 됨.
#img2_bg는 roi영역에서 logo부분이 제거되고 bg만 남게 됨.
img1_fg = cv2.bitwise_and(img1, img1, mask=mask)
img2_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)

#2개의 이미지를 합치면 바탕은 제거되고 logo부분만 합쳐짐.
dst = cv2.add(img1_fg, img2_bg)

#합쳐진 이미지를 원본 이미지에 추가.
img2[0:rows, 0:cols] = dst

cv2.imshow('res', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
##########################
# AIRPLANE & RED SKY 하는 중 
#####################

import cv2
import numpy as np

img_bg  = cv2.imread('images/red_sky.jpg')
image = cv2.imread('images/airplane1.jpg')
image = cv2.resize(image, (200,200))
imageHSV = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
imageGray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

print(imageGray, np.mean(imageGray[:100,:]),np.min(imageGray[:100,:]),np.max(imageGray[:100,:]))

imageThresholded = cv2.inRange(imageHSV, (193, 163, 138), (193, 163, 138))
imageThresholded = cv2.inRange(imageGray,)
mask = cv2.inRange(imageGray,150,161)
mask_inv = cv2.bitwise_not(mask)

result = cv2.bitwise_and(img1, img1, mask=mask)
result_inv = cv2.bitwise_and(roi, roi, mask=mask_inv)

cv2.imshow("Thresholded Image", mask)
cv2.imshow("Original", image)
cv2.imshow("mask_inv",mask_inv)

cv2.waitKey(0)
cv2.destroyAllWindows()


cv2.imshow('res', img2gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

dst =cv2.imread('images/red_sky.jpg')
# 삽입할 이미지의 row, col, channel정보
rows, cols, channels = img1.shape

# 대상 이미지에서 삽입할 이미지의 영역을 추출
roi = img2[0:rows, 0:cols]

# mask를 만들기 위해서 img1을 gray로 변경후 binary image로 전환
# mask는 logo부분이 흰색(255), 바탕은 검은색(0)
# mask_inv는 logo부분이 검은색(0), 바탕은 흰색(255)

img2gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

ret, mask = cv2.threshold(src, 10, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)

#bitwise_and 연산자는 둘다 0이 아닌 경우만 값을 통과 시킴.
#즉 mask가 검정색이 아닌 경우만 통과가 되기때문에 mask영역 이외는 모두 제거됨.
#아래 img1_fg의 경우는 bg가 제거 되고 fg(logo부분)만 남게 됨.
#img2_bg는 roi영역에서 logo부분이 제거되고 bg만 남게 됨.
img1_fg = cv2.bitwise_and(img1, img1, mask=mask)
img2_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)

#2개의 이미지를 합치면 바탕은 제거되고 logo부분만 합쳐짐.
dst = cv2.add(img1_fg, img2_bg)

#합쳐진 이미지를 원본 이미지에 추가.
img2[0:rows, 0:cols] = dst


[[159 159 159 ... 155 155 155]
 [159 159 159 ... 156 157 155]
 [159 159 159 ... 155 156 156]
 ...
 [154 155 153 ... 150 151 152]
 [156 154 154 ... 151 152 152]
 [156 157 154 ... 149 151 151]] 158.47 155 160


In [1]:

#트랙바 생성 lower hue, upper hue 
import cv2
import numpy as np 

def nothing(int):
    pass

img = cv2.imread("images/color_w.png")
img = cv2.resize(img,dsize=(500,500))
img_hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
bg = np.full_like(img,255)
hval, sval, vval = cv2.split(img_hsv)

cv2.namedWindow('colorPicker')
cv2.createTrackbar('lower_hue','colorPicker',30,179,nothing)
cv2.createTrackbar('upper_hue','colorPicker',0,179,nothing)
while True : 
    lo = cv2.getTrackbarPos('lower_hue','colorPicker')
    up = cv2.getTrackbarPos('upper_hue','colorPicker')
    mask = cv2.inRange(hval,lo,up) #lo up 사이에 있으면 흰색, 않으면 검은색 
    mask_inv = cv2.bitwise_not(mask)
    img1 = cv2.bitwise_and(img,img,mask=mask)
    img2 = cv2.bitwise_and(bg,bg,mask=mask_inv)
    cv2.imshow("img1",img1)
    cv2.imshow("img2",img2)
    final_img = cv2.add(img1,img2)
    cv2.imshow("origin",img)
    cv2.imshow("colorPicker",final_img)
    if cv2.waitKey(1) & 0xff ==27:
        break

cv2.destroyAllWindows()
#getHue = cv2.getTrackbarPos('hue','colorPicker')
#이미지 read, convert hsv, h 만 split 해서 inRange 처리 





In [3]:
#크로마키 
#영상에서 객체를 감지하고 구분하는 가장 쉬운 방법은 색상 기반 방법이다. 
#색상 기반 방법을 사용하여 객체를 성공적으로 구분하기 위해서는 
#객체와 배경이 중요한 색상 차이를 가져야 한다. 
import cv2 
import numpy as np 

#img = cv2.imread("images/airplane1.jpg")
img = cv2.imread("images/spring_flower.jpg")
img = cv2.resize(img,dsize=(450,450))
img_bg = cv2.imread("images/lena.jpg")
img_bg = cv2.resize(img_bg,dsize=(450,450))

imgHSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print(imgHSV[:50,:50,0].max(),imgHSV[:50,:50,0].min(),imgHSV[:50,:50,0].mean()) # 107 103 105.189

mask = cv2.inRange(imgHSV,(100,0,0),(104,255,255))
cv2.imshow("mask",mask )
# print(mask)

# mask_inv = cv2.bitwise_not(mask)
# cv2.imshow("mask_inv",mask_inv )
# print(mask_inv.dtype)
# img_f = cv2.bitwise_and(img,img,mask=mask_inv)
# img_b = cv2.bitwise_and(img_bg,img_bg,mask=mask)

# final = cv2.add(img_f,img_b)

# cv2.imshow("final", final)
cv2.imshow("origin", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

104 101 101.9568
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
uint8
