In [11]:
import cv2
import matplotlib.pyplot as plt

img = cv2.imread("./images/airplane1.jpg")
print(img.shape)
print(img)
cv2.imshow("airplane_origin",img)

#img2 = cv2.imread("./images/airplane1.jpg", cv2.IMREAD_GRAYSCALE)
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(img_gray.shape)
print(img_gray)
cv2.imshow("airplane_gray",img_gray)

img_hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
print(img_hsv.shape)
cv2.imshow("airplane_hsv",img_hsv)

img_ycrcb = cv2.cvtColor(img,cv2.COLOR_BGR2YCrCb)
print(img_ycrcb.shape)
cv2.imshow("airplane_ycrcb",img_ycrcb)
cv2.waitKey(0)
cv2.destroyAllWindows()


(427, 640, 3)
[[[193 163 138]
  [193 163 138]
  [193 163 138]
  ...
  [195 162 129]
  [194 161 128]
  [194 161 128]]

 [[193 163 138]
  [193 163 138]
  [193 163 138]
  ...
  [194 161 128]
  [194 161 128]
  [194 161 128]]

 [[193 163 138]
  [193 163 138]
  [193 164 137]
  ...
  [194 161 128]
  [194 161 128]
  [193 160 127]]

 ...

 [[182 158 136]
  [184 160 138]
  [182 158 136]
  ...
  [179 155 133]
  [179 155 133]
  [179 155 133]]

 [[182 158 136]
  [184 160 138]
  [182 158 136]
  ...
  [179 155 133]
  [179 155 133]
  [179 155 133]]

 [[182 158 136]
  [184 160 138]
  [182 158 136]
  ...
  [179 155 133]
  [179 154 134]
  [179 154 134]]]
(427, 640)
[[159 159 159 ... 156 155 155]
 [159 159 159 ... 155 155 155]
 [159 159 159 ... 155 155 154]
 ...
 [154 156 154 ... 151 151 151]
 [154 156 154 ... 151 151 151]
 [154 156 154 ... 151 151 151]]
(427, 640, 3)
(427, 640, 3)


In [20]:
import cv2
import matplotlib.pyplot as plt

img = cv2.imread("./images/airplane1.jpg")
cv2.imshow("airplane_origin",img)
b,g,r =cv2.split(img)
cv2.imshow("b_airplane",b)
cv2.imshow("g_airplane",g)
cv2.imshow("r_airplane",r)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
img = cv2.imread("./images/airplane1.jpg")

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
print(hsv)
hue_val, sat_val, val_val = cv2.split(hsv)

cv2.imshow("src", img)
cv2.imshow("hue",hue_val)
cv2.imshow("saturation",sat_val)
cv2.imshow("value",val_val)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[106  73 193]
  [106  73 193]
  [106  73 193]
  ...
  [105  86 195]
  [105  87 194]
  [105  87 194]]

 [[106  73 193]
  [106  73 193]
  [106  73 193]
  ...
  [105  87 194]
  [105  87 194]
  [105  87 194]]

 [[106  73 193]
  [106  73 193]
  [106  74 193]
  ...
  [105  87 194]
  [105  87 194]
  [105  87 193]]

 ...

 [[106  64 182]
  [106  64 184]
  [106  64 182]
  ...
  [106  66 179]
  [106  66 179]
  [106  66 179]]

 [[106  64 182]
  [106  64 184]
  [106  64 182]
  ...
  [106  66 179]
  [106  66 179]
  [106  66 179]]

 [[106  64 182]
  [106  64 184]
  [106  64 182]
  ...
  [106  66 179]
  [107  64 179]
  [107  64 179]]]


In [21]:
#img = cv2.imread("images\house.jpg")
img = cv2.imread("./images/airplane1.jpg")

img_ycrcb = cv2.cvtColor(img, cv2.COLOR_BGR2YCR_CB)
print(img_ycrcb)
y_luminance, cr_val, cb_val = cv2.split(img_ycrcb)

cv2.imshow("src", img)
cv2.imshow("y_luminance",y_luminance)
cv2.imshow("cr_val",cr_val)
cv2.imshow("cb_val",cb_val)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[159 113 147]
  [159 113 147]
  [159 113 147]
  ...
  [156 109 150]
  [155 109 150]
  [155 109 150]]

 [[159 113 147]
  [159 113 147]
  [159 113 147]
  ...
  [155 109 150]
  [155 109 150]
  [155 109 150]]

 [[159 113 147]
  [159 113 147]
  [159 112 147]
  ...
  [155 109 150]
  [155 109 150]
  [154 109 150]]

 ...

 [[154 115 144]
  [156 115 144]
  [154 115 144]
  ...
  [151 115 144]
  [151 115 144]
  [151 115 144]]

 [[154 115 144]
  [156 115 144]
  [154 115 144]
  ...
  [151 115 144]
  [151 115 144]
  [151 115 144]]

 [[154 115 144]
  [156 115 144]
  [154 115 144]
  ...
  [151 115 144]
  [151 116 144]
  [151 116 144]]]


In [22]:
image = cv2.imread("images\house.jpg")

imageHSV = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

imageThresholded = cv2.inRange(imageHSV, (100,0,0), (120,255,255))

cv2.imshow("Thresholded Image", imageThresholded)
cv2.imshow("Original", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2 
import numpy as np 

img1 = cv2.imread('images/lena.jpg')
img2 = cv2.imread('images/lena.jpg',cv2.IMREAD_GRAYSCALE)

print(img1)
print(img2)





[[[127 136 226]
  [127 136 226]
  [127 136 226]
  ...
  [122 146 234]
  [102 127 213]
  [ 74 100 184]]

 [[128 137 227]
  [128 137 227]
  [127 136 226]
  ...
  [129 149 237]
  [113 134 219]
  [ 87 108 193]]

 [[127 138 228]
  [127 138 228]
  [126 137 227]
  ...
  [132 146 234]
  [117 130 216]
  [ 91 105 188]]

 ...

 [[ 57  19  85]
  [ 61  23  89]
  [ 65  27  93]
  ...
  [ 78  71 176]
  [ 77  68 178]
  [ 73  66 177]]

 [[ 55  17  83]
  [ 61  23  89]
  [ 67  29  95]
  ...
  [ 81  73 180]
  [ 79  72 183]
  [ 78  72 185]]

 [[ 55  17  83]
  [ 61  23  89]
  [ 69  31  97]
  ...
  [ 78  72 181]
  [ 79  72 183]
  [ 78  72 185]]]
[[162 162 162 ... 170 150 122]
 [163 163 162 ... 173 157 131]
 [164 164 163 ... 171 154 128]
 ...
 [ 43  47  51 ... 103 102 100]
 [ 41  47  53 ... 106 106 106]
 [ 41  47  55 ... 105 106 106]]


In [10]:
img1 = np.full((250,250,3),0,dtype=np.uint8)
print(img1)

img2 = np.full((250,250,3),255,dtype=np.uint8)
print(img2)

# cv2.imshow(img1)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255

In [14]:
import cv2 
import cv 
import numpy as np 

x = np.uint8([250])
y = np.uint8([10])
print( cv.add(x,y) ) # 250+10 = 260 => 255
print( x+y ) 

ModuleNotFoundError: No module named 'cv'

In [15]:
#-*- coding:utf-8 -*-
import cv2
import numpy as np

img1 = cv2.imread('images/logo.png')
img2 = cv2.imread('images/lena.jpg')

# 삽입할 이미지의 row, col, channel정보
rows, cols, channels = img1.shape

# 대상 이미지에서 삽입할 이미지의 영역을 추출
roi = img2[0:rows, 0:cols]

#mask를 만들기 위해서 img1을 gray로 변경후 binary image로 전환
#mask는 logo부분이 흰색(255), 바탕은 검은색(0)
#mask_inv는 logo부분이 검은색(0), 바탕은 흰색(255)

img2gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)

#bitwise_and 연산자는 둘다 0이 아닌 경우만 값을 통과 시킴.
#즉 mask가 검정색이 아닌 경우만 통과가 되기때문에 mask영역 이외는 모두 제거됨.
#아래 img1_fg의 경우는 bg가 제거 되고 fg(logo부분)만 남게 됨.
#img2_bg는 roi영역에서 logo부분이 제거되고 bg만 남게 됨.
img1_fg = cv2.bitwise_and(img1, img1, mask=mask)
img2_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)

#2개의 이미지를 합치면 바탕은 제거되고 logo부분만 합쳐짐.
dst = cv2.add(img1_fg, img2_bg)

#합쳐진 이미지를 원본 이미지에 추가.
img2[0:rows, 0:cols] = dst

cv2.imshow('res', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
#-*- coding:utf-8 -*-
import cv2
import numpy as np

img_bg  = cv2.imread('images/red_sky.jpg')
image = cv2.imread('images/airplane1.jpg')
image = cv2.resize(image, (200,200))
imageHSV = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
imageGray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

print(imageGray, np.mean(imageGray[:100,:]),np.min(imageGray[:100,:]),np.max(imageGray[:100,:]))

#imageThresholded = cv2.inRange(imageHSV, (193, 163, 138), (193, 163, 138))
# imageThresholded = cv2.inRange(imageGray,)
# mask = cv2.inRange(imageGray,150,161)
# mask_inv = cv2.bitwise_not(mask)

# result = cv2.bitwise_and(img1, img1, mask=mask)
# result_inv = cv2.bitwise_and(roi, roi, mask=mask_inv)

# cv2.imshow("Thresholded Image", mask)
# cv2.imshow("Original", image)
# cv2.imshow("mask_inv",mask_inv)

# cv2.waitKey(0)
# cv2.destroyAllWindows()


# cv2.imshow('res', img2gray)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# dst =cv2.imread('images/red_sky.jpg')
# # 삽입할 이미지의 row, col, channel정보
# rows, cols, channels = img1.shape

# # 대상 이미지에서 삽입할 이미지의 영역을 추출
# roi = img2[0:rows, 0:cols]

# #mask를 만들기 위해서 img1을 gray로 변경후 binary image로 전환
# #mask는 logo부분이 흰색(255), 바탕은 검은색(0)
# #mask_inv는 logo부분이 검은색(0), 바탕은 흰색(255)

# # img2gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

# ret, mask = cv2.threshold(src, 10, 255, cv2.THRESH_BINARY)
# # mask_inv = cv2.bitwise_not(mask)

# # #bitwise_and 연산자는 둘다 0이 아닌 경우만 값을 통과 시킴.
# # #즉 mask가 검정색이 아닌 경우만 통과가 되기때문에 mask영역 이외는 모두 제거됨.
# # #아래 img1_fg의 경우는 bg가 제거 되고 fg(logo부분)만 남게 됨.
# # #img2_bg는 roi영역에서 logo부분이 제거되고 bg만 남게 됨.
# # img1_fg = cv2.bitwise_and(img1, img1, mask=mask)
# # img2_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)

# # #2개의 이미지를 합치면 바탕은 제거되고 logo부분만 합쳐짐.
# # dst = cv2.add(img1_fg, img2_bg)

# # #합쳐진 이미지를 원본 이미지에 추가.
# # img2[0:rows, 0:cols] = dst


[[159 159 159 ... 155 155 155]
 [159 159 159 ... 156 157 155]
 [159 159 159 ... 155 156 156]
 ...
 [154 155 153 ... 150 151 152]
 [156 154 154 ... 151 152 152]
 [156 157 154 ... 149 151 151]] 158.47 155 160
