In [ ]:
#이미지 변환: 기하변환, 크기, 이동, 회전 
#변환종류 - 
# rigid-body >> 크기X 각도X >> 이동, 회전, 
# similarity >> 크기O 각도X >> 크기 변경
# affine  >> 크기O 각도O 선의수평선X  >>
# perspective >> 크기O 각도O 선의수평선 O >>원근법 



In [11]:
#################
# 입력 파일 기준으로 만들기 (입력 shape 만큼 루프가 돈다 )
################

import cv2
import numpy as np
import matplotlib.pyplot as plt
 
def scale_normal(image,scale_x=1,scale_y=1):
    height,width = image.shape
    _image = np.zeros((int(height*scale_y),int(width*scale_x)),dtype=np.uint8)
    for y in range(height):
        for x in range(width):
            try: 
                _image[int(y*scale_y),int(x*scale_x)] = image[y,x]
            except:
                pass #범위를 넘어가면 pass 
                #print("an exception occured ")

    return _image 

img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
result = scale_normal(img,2,2)
 
cv2.imshow('origin',img)
cv2.imshow('result',result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
#######
## 비어있는 부분을 채우기 
## 나의 방법 

import cv2
import numpy as np
import matplotlib.pyplot as plt
 
def scale_good(image,scale_x=1,scale_y=1):
    height,width = image.shape
    _image = np.zeros((int(height*scale_y),int(width*scale_x)),dtype=np.uint8)
    for y in range(1,height-1):
        for x in range(width-1):
            try: 
                _image[int(y*scale_y),int(x*scale_x)] = image[y,x]
                _image[int(y*scale_y),int(x*scale_x)+1] = image[y,x]     
                _image[int(y*scale_y)-1,int(x*scale_x)] = image[y,x]     
                _image[int(y*scale_y)+1,int(x*scale_x)+1] = image[y,x]     
            except:
                pass #범위를 넘어가면 pass 
                #print("an exception occured ")

    return _image 

img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
result_good2 = scale_good(img,2,2)
result_good1 = scale_good(img,0.5,0.5)
result_normal = scale_normal(img,2,2)

 
cv2.imshow('origin',img)
cv2.imshow('result_good1',result_good1)
cv2.imshow('result_good2',result_good2)
cv2.imshow('result_normal',result_normal)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
###################
# 출력 파일 기준으로 만들기 (입력 shape 만큼 루프가 돈다 )
# 코드의 효율이 좋다 
############

import cv2
import numpy as np
import matplotlib.pyplot as plt
 
def scale_normal(image,scale_x=1,scale_y=1):
    height,width = image.shape
    height_new,width_new = int(height*scale_y),int(width*scale_x)
    _image = np.zeros((height_new,width_new),dtype=np.uint8)
    for y in range(height_new):
        for x in range(width_new):
            try: 
                _image[y,x] = image[int(y/scale_y),int(x/scale_x)]
            except:
                pass #범위를 넘어가면 pass 
                #print("an exception occured ")

    return _image 

img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
result = scale_normal(img,2,2)
 
cv2.imshow('origin',img)
cv2.imshow('result',result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
###################
# 출력 파일 기준으로 만들기 (입력 shape 만큼 루프가 돈다 )
# *interpolation 보간법 기준  
# *scale_nearlest
############

import cv2
import numpy as np
import matplotlib.pyplot as plt
 
def scale_nearlest(image,scale_x=1,scale_y=1):
    height,width = image.shape
    height_new,width_new = int(height*scale_y),int(width*scale_x)
    _image = np.zeros((height_new,width_new),dtype=np.uint8)
    for y in range(height_new):
        for x in range(width_new):
            try: 
                _image[y,x] = image[round(y/scale_y),round(x/scale_x)]
            except:
                pass #범위를 넘어가면 pass 
                #print("an exception occured ")

    return _image 

img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
result = scale_nearlest(img,2,2)
 
cv2.imshow('origin',img)
cv2.imshow('result',result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
import cv2 

img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
print(img.shape)
print(img[511,511])

(512, 512)
106


In [ ]:
#보간법 > 크기 변환만 쓰이지 않는다 
# 이미지 이동, 회전, 변환 
# 선형 : 가중치 
#교수님 코드 참조 


In [28]:
#######
## 이미지 사이즈 줄이기 max_pooling 
######

import cv2
import numpy as np
import matplotlib.pyplot as plt
 
def my_max_pooling(image,size=2):
    
    height,width = image.shape
    _image = np.zeros((int(height/size),int(width/size)),dtype=np.uint8)
    height_new,width_new = _image.shape
    for y in range(1,height_new-1):
        yo = 2*y-1
        #yo = 4*y-3
        for x in range(1,width_new-1):
            try:
                xo = 2*x -1 
                # #xo = 4*x -3 
                max_val = max(image[yo,xo],image[yo,xo+1],image[yo+1,xo],image[yo+1,xo+1])           
                _image[y,x] = max_val   
                       
            except:
                pass #범위를 넘어가면 pass 
                #print("an exception occured ")

    return _image 

def class_max_pooling(image,size=2):
    
    height,width = image.shape
    _image = np.zeros((int(height/size),int(width/size)),dtype=np.uint8)
    height_new,width_new = _image.shape
    for y in range(1,height_new-1):
        for x in range(1,width_new-1):
            try:
                _image[y,x] = np.max(img[2*y:2*y+2,2*x:2*x+2])            
            except:
                pass #범위를 넘어가면 pass 
                #print("an exception occured ")

    return _image 


def class_min_pooling(image,size=2):
    
    height,width = image.shape
    _image = np.zeros((int(height/size),int(width/size)),dtype=np.uint8)
    height_new,width_new = _image.shape
    for y in range(1,height_new-1):
        for x in range(1,width_new-1):
            try:
                _image[y,x] = np.min(img[2*y:2*y+2,2*x:2*x+2])            
            except:
                pass #범위를 넘어가면 pass 
                #print("an exception occured ")

    return _image 

img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
result1 = my_max_pooling(img,2)
result2 = class_max_pooling(img,2)
result3 = class_min_pooling(img,2)
resize_img = cv2.resize(img,dsize=result2.shape,interpolation=cv2.INTER_NEAREST)

cv2.imshow('origin',img)
cv2.imshow('my_max_pooling',result1)
cv2.imshow('class_max_pooling',result2)
cv2.imshow('class_min_pooling',result3)
cv2.imshow('Nearest',scale_nearlest(img,0.5,0.5))
cv2.imshow('resize_img',resize_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#resize default 는 cv2.INTER_LINEAR이다. 

result1 = cv2.resize(img,dsize=(250,250),interpolation=cv2.INTER_NEAREST)
result2 = cv2.resize(img,dsize=(250,250),interpolation=cv2.INTER_MAX)

cv2.imshow("nearest",result1)
cv2.imshow("max",result2)

In [45]:
#이동 

def translate(img, distance=(0,0)):
    height,width = img.shape
    _img = np.zeros((height,width), dtype= np.uint8)
    for y in range(height):
        for x in range(width):
            X = x+distance[0]
            Y = y+distance[1]
            #경계선 검사 
            if(X<0)| (X>=width)| (Y<0)|(Y>=height):
                continue 
            _img[Y,X] = img[y,x]
    
    return _img 



In [46]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
 
image = cv2.imread('images/lena.jpg',cv2.IMREAD_GRAYSCALE)
result = translate(image,distance=(100,100))

cv2.imshow('origin',image)
cv2.imshow('result',result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [52]:
#회전 
def rotate(img, degree=30):
    height,width = img.shape
    _img = np.zeros((height,width), dtype= np.uint8)
    for y in range(height):
        for x in range(width):
            X = int(np.cos(np.radians(degree))*x +np.sin(np.radians(degree))*y)
            Y = int(-np.sin(np.radians(degree))*x +np.cos(np.radians(degree))*y)
            #경계선 검사 
            if(X<0)| (X>=width)| (Y<0)|(Y>=height):
                continue 
            _img[Y,X] = img[y,x]
    
    return _img 


image = cv2.imread('images/lena.jpg',cv2.IMREAD_GRAYSCALE)
result = rotate(image,degree=-30)

cv2.imshow('origin',image)
cv2.imshow('result',result)
#cv2.imshow('result2',result2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [4]:
#90도 단위의 회전은 rotate 
#그 외의 단위 회전은  getRotationMatrix2D 와 warpAffine 함수 

import cv2
import numpy as np
import matplotlib.pyplot as plt
 
img = cv2.imread('images/lena.jpg',cv2.IMREAD_GRAYSCALE)
rows, cols = img.shape

rotate_img = cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
rotate_img2 = cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)
rotate_img3 = cv2.rotate(img,cv2.ROTATE_180)

M = cv2.getRotationMatrix2D((rows/2,cols/2),angle=45, scale=1)
rotate_img4 = cv2.warpAffine(img,M,(rows,cols))

cv2.imshow('rotate_img',rotate_img)
cv2.imshow('rotate_img2',rotate_img2)
cv2.imshow('rotate_img3',rotate_img3)
cv2.imshow('rotate_img4',rotate_img4)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#affine 아핀 => 변환 행렬 필요 => 회전중심점, 각도, 크기 배율 
#getRotationMatrix2D( center, angle, scale ) =>M 
#getAffineTransform(src,dst) => M 

import cv2
import numpy as np
import matplotlib.pyplot as plt
 
rows,cols = img.shape
pts1 = np.float32([[200,100],[400,100],[200,200]])
pts2 = np.float32([[200,300],[400,200],[200,400]])

img = cv2.imread('images/lena.jpg',cv2.IMREAD_GRAYSCALE)
cv2.circle(img,(200,100),10,(0,0,0),-1)
cv2.circle(img,(400,100),10,(0,0,0),-1)
cv2.circle(img,(200,200),10,(0,0,0),-1)

M = cv2.getAffineTransform(pts1,pts2)
dst = cv2.warpAffine(img,M,(cols,rows))
 
cv2.imshow('dst',dst)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


### 과제 
* 원 이미지와 같은 크기의 변환 이미지(빈 이미지)를 윈도우로 출력 
* 원 영상을 출력한 창에서 마우스 클릭한 3 지점을 소스의 영상 좌표로 받는다 
* 변환 이미지에서도 마우스 클릭 3지점 값 받아서 따로 저장 
* warp Affine 이용해서 변환이 warp 되게 프로그램 만들기 

In [26]:
#1. 원 이미지와 같은 크기의 변환 이미지(빈 이미지)를 윈도우로 출력 
import cv2
import numpy as np
import matplotlib.pyplot as plt
 
img = cv2.imread('images/lena.jpg', cv2.IMREAD_GRAYSCALE)
img2 = np.full_like(img,0)

rows,cols = img.shape
pts1 = np.full((3,2),0,dtype=np.float32)
pts2 = np.full((3,2),0,dtype=np.float32)

count_src = -1
count_dst = -1
pts1_flag = 0
pts2_flag = 0 
circles = [] 

#원 영상을 출력한 창에서 마우스 클릭한 3 지점을 소스의 영상 좌표로 받는다 
def mouseHandlerSrc(event,x,y,flags,param ):
    global pts1_flag, count_src,pts1,pts2,img 
    
    if event == cv2.EVENT_LBUTTONDOWN:
        count_src = count_src+1
        if(count_src == 0):
            pts1 = np.full((3,2),0,dtype=np.float32)
            pts1[0]=[x,y]
        elif( count_src ==1):
            pts1[1]=[x,y]
        elif(count_src ==2):
            pts1[2]=[x,y]
            count_src = -1
            pts1_flag = 1
        circles.append((x,y))
        #lo = (x,y)
        #cv2.circle(img,lo,5,(0,0,0),-1)
        
    

def mouseHandlerDst(event,x,y,flags,param ):
    global pts2_flag, count_dst,pts2,img 
    if event == cv2.EVENT_LBUTTONDOWN:
        count_dst = count_dst+1
        if(count_dst == 0):
            pts2 = np.full((3,2),0,dtype=np.float32) 
            pts2[0]=[x,y]
        elif( count_dst ==1):
            pts2[1]=[x,y]
        elif(count_dst ==2):
            pts2[2]=[x,y]          
            count_dst = -1
            pts2_flag=1
        lo = (x,y)
        cv2.circle(img2,lo,5,(255,255,255),-1)      

cv2.namedWindow('imgSrc')
cv2.namedWindow('imgDst')

cv2.setMouseCallback('imgSrc',mouseHandlerSrc) #콜백 함수 
cv2.setMouseCallback('imgDst',mouseHandlerDst) #콜백 함수 


while True :
    cv2.imshow('imgSrc',img)
    cv2.imshow('imgDst',img2)
                       
    if(pts1_flag == 1 and pts2_flag ==1):
        M = cv2.getAffineTransform(pts1,pts2)
        img2 = cv2.warpAffine(img,M,(cols,rows))
        pts1_flag, pts2_flag = 0,0
    if cv2.waitKey(1) & 0xff == 27: 
        break


cv2.destroyAllWindows()

In [11]:
loc_list = np.zeros(3,dtype=np.uint8)
print(loc_list)

rowloc = np.full(3,0,dtype=int)
colloc = np.full(3,0,dtype=int)
location = list(zip(colloc,rowloc))
print(location)

loc_list = np.full((3,2),0)
print(loc_list)

pts1 = np.full((3,2),0)
pts2 = np.full((3,2),0)
print(pts1)
print(pts2)

[0 0 0]
[(0, 0), (0, 0), (0, 0)]
[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]


In [2]:
for index in range(2): 
    print(index)

0
1


In [20]:
pts1[0] = [3,2]
result =np.uint8((3.0,2.0))
print(result.type)

AttributeError: 'numpy.ndarray' object has no attribute 'type'